### PR TITLE
Fix for updated `got` module

### PR DESCRIPTION
**Pull request by EuleHaken**
This should allow for updating to the latest got version.

The code will be cleaned up and tested more by me tomorrow.

See also: Supinic/supibot-package-manager#94

### CODE REVIEW

**Comment by EuleHaken** [comment]
Upon testing locally, I didn't ran into any problems.

**Comment by EuleHaken** [comment]
So there is one problem I am facing now:

The file [command.js](https://github.com/Supinic/supi-core/blob/81455dd8c7d6f5a8b521e3131d49b1437bcb946c/classes/command.js#L713) needs `sb.Got.GotError`, which does no longer exist. I **suppose** that it is now just called `RequestError`, from what I read (used to be [this](https://github.com/sindresorhus/got/blob/v10.7.0/source/errors.ts#L6) now its [this](https://github.com/sindresorhus/got/blob/main/source/core/errors.ts#L19) probably)

**Comment by EuleHaken** [comment]
All problems, that I faced, should now be fixed.

Instead of `gotModule.got()` we could use `gotModule.default()` AFAIK, but I don't think that's much of a problem.

Also, we could add some more request errors into `gotRequestErrors` in the future, but I think for now, this is good.

**Comment by EuleHaken** [comment]
@Supinic regarding the `retry` and `timeout` options, I supposed that:
- for `retry`, we should use
  ```js
  {
    retry: {
      limit: 0
    }
  }
  ```
- and for `timeout`, we should use:
  ```js
  {
    timeout: {
      request: 0
    }
  }
  ```

If you'd like me to use any of [those options](https://github.com/sindresorhus/got/blob/main/documentation/7-retry.md#retry) for `retry` or any of [those options](https://github.com/sindresorhus/got/blob/main/documentation/6-timeout.md#timeout-options) for `timeout`, let me know and I'll change it.

**Review by Supinic — APPROVED** [review]
LGTM

**Pull request merged**
